language: node_js
node_js:
  - "6"

services:
  - docker

cache:
  directories:
    - "node_modules"
    - "vendor"

before_install:
  - npm install bower -g
  - npm install
  - bower install


script: gulp build

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push openmts/webcli;